name: Release and Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Version type to release'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for changelog generation
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate changelog before version bump
        run: |
          # Install conventional-changelog-cli if not present
          pnpm add -g conventional-changelog-cli

          # Generate initial changelog if it doesn't exist
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "All notable changes to this project will be documented in this file." >> CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi

          # Generate changelog for upcoming version
          conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Bump version
        id: version
        run: |
          # Update version based on input
          pnpm run version:${{ inputs.version-type }}

          # Get new version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "new_version=v$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "version_number=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Build project
        run: pnpm run build

      - name: Run linting
        run: pnpm run lint

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore(release): bump version to ${{ steps.version.outputs.new_version }}" || echo "No changes to commit"

      - name: Create Git tag
        run: git tag ${{ steps.version.outputs.new_version }}

      - name: Push changes and tag
        run: |
          git push origin master
          git push origin ${{ steps.version.outputs.new_version }}

      - name: Publish to NPM
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version.outputs.new_version }}
          release_name: Release ${{ steps.version.outputs.new_version }}
          body: |
            ## Changes in ${{ steps.version.outputs.new_version }}

            This release includes improvements and updates to the Original.land AI Agent integration for n8n.

            **Version Type**: ${{ inputs.version-type }}

            ### Installation
            ```bash
            pnpm add @original-land/n8n-nodes-original-embed@${{ steps.version.outputs.version_number }}
            ```

            ### What's Changed
            Check the [CHANGELOG.md](https://github.com/noku-team/n8n-original-embedding/blob/master/CHANGELOG.md) for detailed information.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify completion
        run: |
          echo "✅ Release ${{ steps.version.outputs.new_version }} completed successfully!"
          echo "📦 Published to NPM: https://www.npmjs.com/package/@original-land/n8n-nodes-original-embed"
          echo "🏷️ GitHub Release: https://github.com/noku-team/n8n-original-embedding/releases/tag/${{ steps.version.outputs.new_version }}"
